# Generated by Django 5.2.8 on 2025-11-25 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='source_files/')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_ocr_processed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_source_journals', to='compta.journal')),
            ],
        ),
        migrations.CreateModel(
            name='FormSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_source_journals', to='compta.journal')),
            ],
        ),
    ]
