# Generated by Django 5.2.8 on 2025-11-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
