# Generated by Django 5.2.8 on 2025-12-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesource',
            name='hash_ocr',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
