# Generated by Django 5.2.8 on 2025-11-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0003_remove_journal_file_source_and_more'),
        ('ocr', '0002_remove_filesource_journal_remove_formsource_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesource',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_sources', to='compta.journal'),
        ),
        migrations.AddField(
            model_name='formsource',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_sources', to='compta.journal'),
        ),
    ]
