# Generated by Django 5.2.8 on 2025-12-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_filesource_hash_ocr'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsource',
            name='ref_file',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='formsource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsource',
            name='piece_type',
            field=models.CharField(blank=True, default='Autres', max_length=225, null=True),
        ),
    ]
