# Generated by Django 5.2.8 on 2025-12-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_formsource_ref_file_alter_formsource_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesource',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='formsource',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
