from compta import views
from compta.dashboard_view_optimized import dashboard_indicators_view
from django.urls import path

urlpatterns = [
    # === PROJECTS ===
    path("projects/", views.ProjectListCreateView.as_view(), name="project-list-create"),
    path("projects/<int:id>/", views.ProjectDetailView.as_view(), name="project-detail"),
    path("projects/user-active/", views.UserProjectsView.as_view(), name="user-projects"),
    path("projects/request-access/", views.ProjectAccessRequestView.as_view(), name="request-project-access"),
    path("projects/manage-access/", views.ManageAccessRequestsView.as_view(), name="manage-project-access"),

    path("journals/generate/", views.generate_journal_view, name="generate-journal"),
    path("journals/", views.list_journals_view, name="list-journals"),
    path("journals/repartition/", views.journal_repartition_view, name="journal-repartition"),
    path("dashboard/indicators/", dashboard_indicators_view, name="dashboard-indicators"),
    path("dashboard/ai-analysis/", views.ai_dashboard_analysis_view, name="ai-dashboard-analysis"),
    path("journals/date-range/", views.journal_date_range_view, name="journal-date-range"),
    path("balance/generale/", views.balance_generale_view, name="balance-generale"),
    path("bilans/", views.BilanListCreateView.as_view(), name="list-bilan"),
    path("bilans/<int:id>/", views.BilanDetailView.as_view(), name="detail-bilan"),
    path("bilans/manual/", views.create_bilan_manual_view, name="create-bilan-manual"),
    path("CompteResultats/", views.CompteResultatListCreateView.as_view(), name="list-CompteResultat"),
    path("CompteResultats/<int:id>/", views.CompteResultatDetailView.as_view(), name="detail-CompteResultat"),
    path("CompteResultats/manual/", views.create_compte_resultat_manual_view, name="create-compte-resultat-manual"),
    path("chiffre-affaire/", views.chiffre_affaire_view, name="chiffre-affaire"),
    path("ebe/", views.ebe_view, name="ebe"),
    path("resultat-net/", views.resultat_net_view, name="resultat-net"),
    path("marge-brute/", views.marge_brute_view, name="marge-brute"),
    path("bfr/", views.bfr_view, name="bfr"),
    path("caf/", views.caf_view, name="caf"),
    path("leverage-brut/", views.leverage_brut_view, name="leverage-brut"),
    path("annuite-caf/", views.annuite_caf_view, name="annuite-caf"),
    path("dette-lmt-caf/", views.dette_lmt_caf_view, name="dette-lmt-caf"),
    path("resultat-net-ca/",views.resultat_net_ca_view,name="resultat-net-ca"),
    path("marge-nette/", views.marge_nette_view, name="marge-nette"),
    path("tresorerie/", views.tresorerie_view, name="tresorerie"),
    path("charge-ebe/", views.charge_ebe_view, name="charge-ebe"),
    path("charge-ca/", views.charge_ca_view, name="charge-ca"),
    # path("marge-endettement/", views.marge_endettement_view, name="marge-endettement"),
    path("roe/", views.roe_view, name="roe"),
    path("roa/", views.roa_view, name="roa"),
    path("current-ratio/", views.current_ratio_view, name="current-ratio"),
    path("quick-ratio/", views.quick_ratio_view, name="quick-ratio"),
    path("gearing/", views.gearing_view, name="gearing"),
    path("rotation-stock/", views.rotation_stock_view, name="rotation-stock"),
    path("marge-operationnelle/", views.marge_operationnelle_view, name="marge-operationnelle"),
    path("repartition-resultat/",views.repartition_produits_charges_view,name="repartition-resultat"),
    path("evolution-tresorerie/",views.evolution_tresorerie_view,name="evolution-tresorerie"),
    path("evolution-marges/",views.evolution_marges_view,name="evolution-marges"),
    path("evolution-caf/",views.evolution_caf_view,name="evolution-caf"),
    path("evolution-marge-operationnelle/",views.evolution_marge_operationnelle_view,name="evolution-marge-operationnelle"),
    path("evolution-roe/",views.evolution_roe_view,name="evolution-roe"),
    path("evolution-roa/",views.evolution_roa_view,name="evolution-roa"),
    path('evolution-ca-resultat/', views.evolution_ca_resultat_view, name='evolution-ca-resultat'), # NEW OPTIMIZED ENDPOINT
    path("top-comptes-mouvementes/",views.top_comptes_mouvementes_view,name="top-comptes-mouvementes"),
    # path("chiffre-affaire-mensuel/",views.chiffre_affaire_mensuel_view,name="chiffre-affaire-mensuel"),
    # path("chiffre-affaire-annuel/",views.chiffre_affaire_annuel_view,name="chiffre-affaire-annuel"),
    path("journals/years/", views.get_available_years_view, name="available-years"),
    path("bilan-kpis-variations/", views.bilan_kpis_with_variations_view, name="bilan-kpis-variations"),
    path("tva/", views.tva_view, name="tva"),
    path("amortissements-exercice/", views.amortissements_exercice_view, name="amortissements-exercice"),
    path("delais-clients/", views.delais_clients_view, name="delais-clients"),
    path("delais-fournisseurs/", views.delais_fournisseurs_view, name="delais-fournisseurs"),
    path("compte-resultat/ai-analysis/", views.compte_resultat_ai_analysis_view, name="compte-resultat-ai-analysis"),
]
    #path("journals/", views.list_journals_view, name="list-journals"),
    # path("comptes/", views.list_comptes, name="list-comptes"),
    # path("grand-livre/", views.grand_livre, name="grand-livre"),
    # path("bilans/", views.bilans_view, name="bilans"),
    # path("CompteResultats/", views.CompteResultat_view, name="compte-resultat"),
