from compta import views
from django.urls import path

urlpatterns = [
    path("journals/generate/", views.generate_journal_view, name="generate-journal"),
    path("journals/", views.list_journals_view, name="list-journals"),
    path("journals/repartition/", views.journal_repartition_view, name="journal-repartition"),
    path("dashboard/indicators/", views.dashboard_indicators_view, name="dashboard-indicators"),
    path("journals/date-range/", views.journal_date_range_view, name="journal-date-range"),
    path("balance/generale/", views.balance_generale_view, name="balance-generale"),
    path("bilans/", views.BilanListCreateView.as_view(), name="list-bilan"),
    path("CompteResultats/", views.CompteResultatListCreateView.as_view(), name="list-CompteResultat"),
    path("chiffre-affaire/", views.chiffre_affaire_view, name="chiffre-affaire"),
    path("ebe/", views.ebe_view, name="ebe"),
    path("resultat-net/", views.resultat_net_view, name="resultat-net"),
    path("bfr/", views.bfr_view, name="bfr"),
    path("caf/", views.caf_view, name="caf"),
    path("leverage-brut/", views.leverage_brut_view, name="leverage-brut"),
    path("annuite-caf/", views.annuite_caf_view, name="annuite-caf"),
    path("dette-lmt-caf/", views.dette_lmt_caf_view, name="dette-lmt-caf"),
    path("resultat-net-ca/",views.resultat_net_ca_view,name="resultat-net-ca"),
    path("marge_net/",views.marge_net_view,name="marge_net"),
    path("charge-ebe/", views.charge_ebe_view, name="charge-ebe"),
    path("charge-ca/", views.charge_ca_view, name="charge-ca"),
    # path("marge-endettement/", views.marge_endettement_view, name="marge-endettement"),
    # path("roe/", views.roe_view, name="roe"),
    # path("roa/", views.roa_view, name="roa"),
    # path("current-ratio/", views.current_ratio_view, name="current-ratio"),
    # path("quick-ratio/", views.quick_ratio_view, name="quick-ratio"),
    # path("gearing/", views.gearing_view, name="gearing"),
    # path("rotation-stock/", views.rotation_stock_view, name="rotation-stock"),
    # path("marge-operationnelle/", views.marge_operationnelle_view, name="marge-operationnelle"),
    # path("repartition-resultat/",views.repartition_produits_charges_view,name="repartition-resultat"),
    # path("evolution-tresorerie/",views.evolution_tresorerie_view,name="evolution-tresorerie"),
    # path("top-comptes-mouvementes/",views.top_comptes_mouvementes_view,name="top-comptes-mouvementes"),
    # path("chiffre-affaire-mensuel/",views.chiffre_affaire_mensuel_view,name="chiffre-affaire-mensuel"),
    # path("chiffre-affaire-annuel/",views.chiffre_affaire_annuel_view,name="chiffre-affaire-annuel"),
    path("journals/years/", views.get_available_years_view, name="available-years"),
    path("bilan-kpis-variations/", views.bilan_kpis_with_variations_view, name="bilan-kpis-variations"),
]
    #path("journals/", views.list_journals_view, name="list-journals"),
    # path("comptes/", views.list_comptes, name="list-comptes"),
    # path("grand-livre/", views.grand_livre, name="grand-livre"),
    # path("bilans/", views.bilans_view, name="bilans"),
    # path("CompteResultats/", views.CompteResultat_view, name="compte-resultat"),
