# Generated by Django 5.2.8 on 2025-11-19 07:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(db_index=True, max_length=20, unique=True)),
                ('intitule_du_compte', models.CharField(max_length=255)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('solde_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('solde_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'balance',
                'ordering': ['numero_compte'],
                'indexes': [models.Index(fields=['date'], name='balance_date_de66f5_idx'), models.Index(fields=['numero_compte', 'date'], name='balance_numero__48c70a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(db_index=True, max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('montant_ar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nature', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(db_index=True)),
                ('type_bilan', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif')], db_index=True, max_length=10)),
                ('categorie', models.CharField(choices=[('ACTIF_IMMOBILISE', 'Actif immobilisé'), ('ACTIF_CIRCULANT', 'Actif circulant'), ('TRESORERIE_ACTIF', 'Trésorerie - Actif'), ('CAPITAUX_PROPRES', 'Capitaux propres'), ('PROVISIONS', 'Provisions'), ('DETTES', 'Dettes'), ('TRESORERIE_PASSIF', 'Trésorerie - Passif')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilans', to='compta.balance', verbose_name='Balance source')),
            ],
            options={
                'db_table': 'bilan',
                'ordering': ['date', 'type_bilan', 'categorie', 'numero_compte'],
            },
        ),
        migrations.CreateModel(
            name='AnnexeComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('section', models.CharField(max_length=100)),
                ('rubrique', models.CharField(max_length=200)),
                ('commentaire_donnee', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bilan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annexes', to='compta.bilan', verbose_name='Bilan associé')),
            ],
            options={
                'db_table': 'annexe_comptable',
                'ordering': ['date', 'section', 'rubrique'],
            },
        ),
        migrations.CreateModel(
            name='CompteResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(db_index=True, max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('montant_ar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nature', models.CharField(choices=[('CHARGE', 'Charge'), ('PRODUIT', 'Produit')], db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_resultat', to='compta.balance', verbose_name='Balance source')),
            ],
            options={
                'db_table': 'compte_resultat',
                'ordering': ['date', 'nature', 'numero_compte'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('numero_piece', models.CharField(max_length=50)),
                ('type_journal', models.CharField(choices=[('ACHAT', 'Journal des achats'), ('VENTE', 'Journal des ventes'), ('BANQUE', 'Journal de banque'), ('CAISSE', 'Journal de caisse'), ('OD', 'Journal des opérations diverses'), ('AN', 'Journal des à-nouveaux')], max_length=20)),
                ('numero_compte', models.CharField(db_index=True, max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('debit_ar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_ar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'journal',
                'ordering': ['date', 'numero_piece'],
                'indexes': [models.Index(fields=['date', 'type_journal'], name='journal_date_55e931_idx'), models.Index(fields=['numero_compte', 'date'], name='journal_numero__ea7491_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrandLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('date', models.DateField(db_index=True)),
                ('numero_piece', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grand_livre_entries', to='compta.journal', verbose_name='Écriture journal')),
            ],
            options={
                'db_table': 'grand_livre',
                'ordering': ['numero_compte', 'date', 'numero_piece'],
            },
        ),
        migrations.AddIndex(
            model_name='bilan',
            index=models.Index(fields=['date', 'type_bilan'], name='bilan_date_1288db_idx'),
        ),
        migrations.AddIndex(
            model_name='bilan',
            index=models.Index(fields=['type_bilan', 'categorie'], name='bilan_type_bi_48f331_idx'),
        ),
        migrations.AddIndex(
            model_name='annexecomptable',
            index=models.Index(fields=['date', 'section'], name='annexe_comp_date_a98ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='compteresultat',
            index=models.Index(fields=['date', 'nature'], name='compte_resu_date_8f119d_idx'),
        ),
        migrations.AddIndex(
            model_name='compteresultat',
            index=models.Index(fields=['numero_compte'], name='compte_resu_numero__e271f3_idx'),
        ),
        migrations.AddIndex(
            model_name='grandlivre',
            index=models.Index(fields=['numero_compte', 'date'], name='grand_livre_numero__437818_idx'),
        ),
        migrations.AddIndex(
            model_name='grandlivre',
            index=models.Index(fields=['date'], name='grand_livre_date_b7bcc8_idx'),
        ),
    ]
