# Generated by Django 5.2.8 on 2025-11-14 13:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnexeComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('section', models.CharField(max_length=100)),
                ('rubrique', models.CharField(max_length=200)),
                ('commentaire_donnee', models.TextField(verbose_name='Commentaire / Donnée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annexe Comptable',
                'verbose_name_plural': 'Annexes Comptables',
                'db_table': 'annexe_comptable',
                'ordering': ['date', 'section', 'rubrique'],
                'indexes': [models.Index(fields=['date', 'section'], name='annexe_comp_date_a98ab3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(db_index=True, max_length=20)),
                ('intitule_du_compte', models.CharField(max_length=255)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('solde_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('solde_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'db_table': 'balance',
                'ordering': ['numero_compte', 'date'],
                'indexes': [models.Index(fields=['date'], name='balance_date_de66f5_idx'), models.Index(fields=['numero_compte', 'date'], name='balance_numero__48c70a_idx')],
                'constraints': [models.UniqueConstraint(fields=('numero_compte', 'date'), name='unique_balance_compte_date')],
            },
        ),
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(db_index=True, max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('montant_ar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (Ar)')),
                ('nature', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(db_index=True)),
                ('type_bilan', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif')], db_index=True, max_length=10)),
                ('categorie', models.CharField(choices=[('ACTIF_IMMOBILISE', 'Actif immobilisé'), ('ACTIF_CIRCULANT', 'Actif circulant'), ('TRESORERIE_ACTIF', 'Trésorerie - Actif'), ('CAPITAUX_PROPRES', 'Capitaux propres'), ('PROVISIONS', 'Provisions'), ('DETTES', 'Dettes'), ('TRESORERIE_PASSIF', 'Trésorerie - Passif')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bilan',
                'verbose_name_plural': 'Bilans',
                'db_table': 'bilan',
                'ordering': ['date', 'type_bilan', 'categorie', 'numero_compte'],
                'indexes': [models.Index(fields=['date', 'type_bilan'], name='bilan_date_1288db_idx'), models.Index(fields=['type_bilan', 'categorie'], name='bilan_type_bi_48f331_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompteResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(db_index=True, max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('montant_ar', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (Ar)')),
                ('nature', models.CharField(choices=[('CHARGE', 'Charge'), ('PRODUIT', 'Produit')], db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte de Résultat',
                'verbose_name_plural': 'Comptes de Résultat',
                'db_table': 'compte_resultat',
                'ordering': ['date', 'nature', 'numero_compte'],
                'indexes': [models.Index(fields=['date', 'nature'], name='compte_resu_date_8f119d_idx'), models.Index(fields=['numero_compte'], name='compte_resu_numero__e271f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrandLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('numero_piece', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('solde', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grand Livre',
                'verbose_name_plural': 'Grand Livre',
                'db_table': 'grand_livre',
                'ordering': ['date', 'numero_piece'],
                'indexes': [models.Index(fields=['date'], name='grand_livre_date_b7bcc8_idx'), models.Index(fields=['numero_piece'], name='grand_livre_numero__35b784_idx')],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('numero_piece', models.CharField(max_length=50)),
                ('type_journal', models.CharField(choices=[('ACHAT', 'Journal des achats'), ('VENTE', 'Journal des ventes'), ('BANQUE', 'Journal de banque'), ('CAISSE', 'Journal de caisse'), ('OD', 'Journal des opérations diverses'), ('AN', 'Journal des à-nouveaux')], max_length=20)),
                ('numero_compte', models.CharField(db_index=True, max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('debit_ar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Débit (Ar)')),
                ('credit_ar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédit (Ar)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'db_table': 'journal',
                'ordering': ['date', 'numero_piece'],
                'indexes': [models.Index(fields=['date', 'type_journal'], name='journal_date_55e931_idx'), models.Index(fields=['numero_compte', 'date'], name='journal_numero__ea7491_idx')],
            },
        ),
    ]
