# Generated by Django 5.2.8 on 2025-11-21 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
        ('ocr', '0002_filesource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='file_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='ocr.filesource'),
        ),
    ]
