# Generated by Django 5.2.8 on 2025-11-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
        ('ocr', '0002_remove_filesource_journal_remove_formsource_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='file_source',
            field=models.ManyToManyField(blank=True, null=True, related_name='file_source_journals', to='ocr.filesource'),
        ),
        migrations.AddField(
            model_name='journal',
            name='form_source',
            field=models.ManyToManyField(blank=True, null=True, related_name='form_source_journals', to='ocr.formsource'),
        ),
    ]
