# Generated by Django 5.2.8 on 2026-01-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='categorie',
            field=models.CharField(choices=[('ACTIF_COURANTS', 'Actif courants'), ('ACTIF_NON_COURANTS', 'Actif non courants'), ('CAPITAUX_PROPRES', 'Capitaux propres'), ('PASSIFS_COURANTS', 'Passifs courants'), ('PASSIFS_NON_COURANTS', 'Passifs non courants')], max_length=30),
        ),
    ]
