# Generated by Django 5.2.8 on 2025-11-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0002_journal_file_source_journal_form_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='file_source',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='form_source',
        ),
    ]
